### ISSUE TITLE
Pulling master on every submodule doesn't even build

### ISSUE THREAD

**Issue by ghost** [thirddegree/Hatchit#2]
This is totes bad @Honeybunch @MattGuerrette

**Comment by MattGuerrette** [comment]
Unless we had merged the work we have done in dev into master on every submoduble. I wouldn't expect it to.

**Comment by ghost** [comment]
We need some sort of system so that if commits end up breaking the build, we have something to roll back to, and currently we have no system to do so.  That's the bigger problem.  Without something like that, we effectively have the same source control as sharing a Dropbox account

**Comment by ghost** [comment]
We don't even have any record of successful commit combinations to make a build in the first place.

**Comment by raselneck** [comment]
Doesn't git have a way to roll back to a certain commit?

**Comment by MattGuerrette** [comment]
It does. You checkout the specific commit hash.....

**Comment by raselneck** [comment]
Yeah, so couldn't we just use that? Isn't git our roll back solution?

**Comment by ghost** [comment]
I mean, with the submodules do we know when we rollback a specific module what commits from the other modules correlate with that commit?

**Comment by raselneck** [comment]
I'm still not sure if I follow. Would it be easier to explain in class tomorrow?

**Comment by ghost** [comment]
I guess, better to just explain in class than fill this message board
