### ISSUE TITLE
Error C2039 'back_inserter': is not a member of 'std'

### ISSUE THREAD

**Issue by VagueLobster** [thirddegree/Hatchit#21]
How to fix this? i'm currently trying to build the four Hatchit modules...

**Comment by MattGuerrette** [comment]
Are you building on Windows? If so, are you using Visual Studio 2015?

Building Hatchit on Windows **requires** Visual Studio 2015 for C++11 features.

If you are building on Linux, then any C++11/14 compliant compiler will work.

**Comment by VagueLobster** [comment]
yeah im currently using windows 10 not anniversary edition, and i am using visual studio 2015 community edition

**Comment by VagueLobster** [comment]
i will try something first and then i'll report back... ok?

**Comment by MattGuerrette** [comment]
I've updated the build instructions for Windows btw. Please check and make sure you did the same.

One thing that could be causing an issue is that your projects are not using the Windows 10 SDK, but rather falling back to the 8.1 SDK.

I would recommend right clicking the project or solution and trying to retarget it and check what SDK its using.

**Comment by VagueLobster** [comment]
i can build the debug version of all four Hatchit modules but only two of them when in release mode...

**Comment by VagueLobster** [comment]
in release i cannot build graphics or game, and in every four modules it is targeted for window 10, i have checked as you suggested :)

**Comment by MattGuerrette** [comment]
Ahh k. I'll test this myself then and get a fix. :)

**Comment by VagueLobster** [comment]
thanks and i'll definitely look forward to it :)

**Comment by MattGuerrette** [comment]
Okay, I've submitted a fix.

https://github.com/thirddegree/HatchitGraphics/commit/7e8d41171047c60bb99c61131eeeecd6dc217dab

**Comment by VagueLobster** [comment]
It works! Thanks alot Matt :)
