### ISSUE TITLE
Need to merge master branch of each module into dev

### ISSUE THREAD

**Issue by MattGuerrette** [thirddegree/Hatchit#22]
Since this project is being revived and I see interest from others, all future work should be done in a dev branch rather than pulling everything into master.

The master branch will be reserved for update releases.

**Comment by FirefoxMetzger** [comment]
So you are using a feature branch / central repo gitflow? If so should pull requests go to the development or master branch?

**Comment by Honeybunch** [comment]
please submit PRs to the dev branch

**Comment by MattGuerrette** [comment]
Yes, as Honeybunch stated. All work should be submitted in a PR to the dev branch. Though you are free to make feature branches on your fork. The PR must go to the dev branch tho
