### ISSUE TITLE
Convert contributing guides from PDF to GH Wiki

### ISSUE THREAD

**Issue by justwheel** [thirddegree/Hatchit#24]
As an idea, it might be helpful and easier to maintain if the contributing guidelines in the `doc/` folder on the `dev` branch were instead converted to a GitHub wiki page. Ideally, this will make it easier to edit and update on the fly and also allow other contributors to expand or add on as necessary. Just a thought. :smile:

**Comment by MattGuerrette** [comment]
Yea this sounds like a good idea. I'll work on this today.

**Comment by MattGuerrette** [comment]
I've added the initial contributing document to the wiki. It still needs further work, but it is there now.
